# Configuration for welcome - https://github.com/behaviorbot/welcome
newIssueWelcomeComment: >
  Thanks for opening your first issue here! 🎉 Be sure to follow the issue template and provide as much detail as possible! 🚀

newPRWelcomeComment: >
  Thanks for opening this pull request! 🎉 Please check out our contributing guidelines and ensure your code meets the required standards. 😊

firstPRMergeComment: >
  🥳 Congrats on merging your first pull request! We here at behaviorbot are super proud of you! Keep contributing! 💪✨
