credentials:
  usernames:
    harsh:
      email: harsh432004@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Harsh Vaidya
      password: abc # Will be hashed automatically
    harsh04:
      email: 22bt04154@gsfcuniversity.ac.in
      failed_login_attempts: 0 # Will be managed automatically
      logged_in: False # Will be managed automatically
      name: Harshu
      password: def # Will be hashed automatically
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
pre-authorized:
  emails:
  - melsby@gmail.com

