name: 'Greetings'

on:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

permissions:
  issues: write
  pull-requests: write

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Sending a custom greeting message to issues and PRs using peter-evans/welcome
      - name: Welcome new issue or PR
        uses: peter-evans/welcome@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Welcome, @${{ github.actor }}! Your issue is like a spark that ignites innovation. We're thrilled to dive into it and work together to find a solution."
          pr-message: "Great job, @${{ github.actor }}! 🎉 Thank you for opening a pull request. Your contribution is valuable and we appreciate your efforts to improve our project."
          footer: "Soon the maintainers/owner will review it and provide you with feedback/suggestions."
